### ISSUE TITLE
Error while making commons

### ISSUE THREAD

**Issue by saheel1115** [GumTreeDiff/cgum#1]
Hello! I am trying to compile cgum so that I can use the binary to process C files using Gumtree. However, while running make I run into the following error. Can someone help me resolve it?

```
make[2]: Entering directory `/home/saheel/cgum/commons'
ocamlc.opt -g  -I ocamlextra -I ocollection  -g  -I ocamlextra -I ocollection   -c ocamlextra/dumper.ml
File "ocamlextra/dumper.ml", line 1:
Error: Could not find the .cmi file for interface ocamlextra/dumper.mli.
```

Thanks!

**Comment by JuliaLawall** [comment]
Try make clean, make depend, make

**Comment by saheel1115** [comment]
That worked! Thanks!

**Comment by sidharththapar** [comment]
@saheel1115 @JuliaLawall  what does make do? how will it help resolving the error-
java.io.IOException: Cannot run program "cgum" (in directory "/var/folders/7b/2c5j3yld1xs6_qtxmx3mvyhc0000gn/T"): error=2, No such file or directory

**Comment by jrfaller** [comment]
Hi, make will create a cgum binary that you have to put in your system path to resolve this error.

**Comment by sidharththapar** [comment]
make depend gives the following error:
ocamldep -I commons -I commons/ocamlextra -I globals -I parsing_c *.mli *.ml > .depend
/bin/sh: ocamldep: command not found
make: *** [depend] Error 127

**Comment by jrfaller** [comment]
you need a proper ocaml installation
