### ISSUE TITLE
make issue with ocaml compiler

### ISSUE THREAD

**Issue by xiaotili0123** [GumTreeDiff/cgum#10]
When I make the cgum, it always comes with errors like this:
Error: ocamlextra/dumper.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
Makefile:199: recipe for target 'common.cmo' failed
make[2]: *** [common.cmo] Error 2
make[2]: Leaving directory '/home/xxl237/cgum/commons'
Makefile:141: recipe for target 'subdirs' failed
make[1]: *** [subdirs] Error 2
make[1]: Leaving directory '/home/xxl237/cgum'
Makefile:131: recipe for target 'byte' failed
make: *** [byte] Error 2

I tried different versions of ocaml, but still won't work. Could you please help with this, also it would be great if you can improve the document about how to apply cgum in gumtree to parse the difference between two C files. I find it difficult to look for the related operations.

**Comment by JuliaLawall** [comment]
On Sun, 22 Sep 2019, Crystal_Lee wrote:

>
> When I make the cgum, it always comes with errors like this:
> Error: ocamlextra/dumper.cmi
> is not a compiled interface for this version of OCaml.
> It seems to be for a newer version of OCaml.
> Makefile:199: recipe for target 'common.cmo' failed
> make[2]: *** [common.cmo] Error 2
> make[2]: Leaving directory '/home/xxl237/cgum/commons'
> Makefile:141: recipe for target 'subdirs' failed
> make[1]: *** [subdirs] Error 2
> make[1]: Leaving directory '/home/xxl237/cgum'
> Makefile:131: recipe for target 'byte' failed
> make: *** [byte] Error 2
>
> I tried different versions of ocaml, but still won't work. Could you please
> help with this, also it would be great if you can improve the document about
> how to apply cgum in gumtree to parse the difference between two C files. I
> find it difficult to look for the related operations.

The file that it complains about should be a generate file.  Perhaps it
would solve the problem just to remove it.

julia

**Comment by xiaotili0123** [comment]
make subdirs
make[1]: Entering directory '/home/xxl237/cgum'
make -C commons OCAMLCFLAGS="-g " OPTFLAGS="-g"
make[2]: Entering directory '/home/xxl237/cgum/commons'
ocamlc.opt -g  -I ocamlextra -I ocollection  -g  -I ocamlextra -I ocollection   -c common.ml
File "./common.ml", line 1159, characters 14-33:
Error: Unbound module Commands
Makefile:199: recipe for target 'common.cmo' failed
make[2]: *** [common.cmo] Error 2
make[2]: Leaving directory '/home/xxl237/cgum/commons'
Makefile:141: recipe for target 'subdirs' failed
make[1]: *** [subdirs] Error 2
make[1]: Leaving directory '/home/xxl237/cgum'
Makefile:131: recipe for target 'byte' failed
make: *** [byte] Error 2

Then it comes with the new error, I am using ocaml 4.04.0 right now.

**Comment by JuliaLawall** [comment]
On Sun, 22 Sep 2019, Crystal_Lee wrote:

>
> make subdirs
> make[1]: Entering directory '/home/xxl237/cgum'
> make -C commons OCAMLCFLAGS="-g " OPTFLAGS="-g"
> make[2]: Entering directory '/home/xxl237/cgum/commons'
> ocamlc.opt -g -I ocamlextra -I ocollection -g -I ocamlextra -I ocollection
> -c common.ml
> File "./common.ml", line 1159, characters 14-33:
> Error: Unbound module Commands
> Makefile:199: recipe for target 'common.cmo' failed
> make[2]: *** [common.cmo] Error 2
> make[2]: Leaving directory '/home/xxl237/cgum/commons'
> Makefile:141: recipe for target 'subdirs' failed
> make[1]: *** [subdirs] Error 2
> make[1]: Leaving directory '/home/xxl237/cgum'
> Makefile:131: recipe for target 'byte' failed
> make: *** [byte] Error 2
>
> Then it comes with the new error, I am using ocaml 4.04.0 right now.

I had the same problem as you had originally after a git pull.  But then
after a make clean, all was fine.  I have OCaml version 4.07.0.

julia

**Comment by xiaotili0123** [comment]
I see. That works for me. Thank you so much. I tried version 4.07.0 initially as well and came with the same error. So I guess it is not the problem of version compatibility as the error message suggests.
