### ISSUE TITLE
Port cgum to new GumTree's XML format

### ISSUE THREAD

**Issue by jrfaller** [GumTreeDiff/cgum#13]
Currently, cgum produces such an XML :
~~~
<tree type = "350100" label = "" typeLabel = "DeclList" pos = "27" length = "10" line_before = "3" col_before = "1" line_after = "3" col_after = "11">
     <tree type = "480000" label = "b" typeLabel = "GenericString" pos = "31" length = "1" line_before = "3" col_before = "5" line_after = "3" col_after = "6"/>
      <tree type = "360100" label = "" typeLabel = "InitExpr" pos = "35" length = "1" line_before = "3" col_before = "9" line_after = "3" col_after = "10">
       <tree type = "240200" label = "0" typeLabel = "Constant" pos = "35" length = "1" line_before = "3" col_before = "9" line_after = "3" col_after = "10"/>
      </tree>
    </tree>
~~~

We have updated gumtree so that we require less information to exchange ASTs, the new format is like that :

~~~
<root>
<context></context>
<tree type="Module" pos="0" length="105">
  <tree type="Import" pos="0" length="12">
    <tree type="alias" label="whois" pos="0" length="6">
    </tree>
  </tree>
</tree>
</root>
~~~

I don't know if it's easy to retrieve pos and length instead of columns / lines, but I bet the modifications on type being now the same as typeLabel, typeLabel being removed, and label being optional should be easy to implement.

@npalix Do you know where I should look for this?

Cheers!

**Comment by JuliaLawall** [comment]
On Fri, 4 Oct 2019, Jean-Rémy Falleri wrote:

>
> Currently, cgum produces such an XML :
>
> <tree type = "350100" label = "" typeLabel = "DeclList" pos = "27" length = "10" line_before = "3" col_before = "1" line_after = "3" col_after = "11">
>      <tree type = "480000" label = "b" typeLabel = "GenericString" pos = "31" length = "1" line_before = "3" col_before = "5" line_after = "3" col_after = "6"/>
>       <tree type = "360100" label = "" typeLabel = "InitExpr" pos = "35" length = "1" line_before = "3" col_before = "9" line_after = "3" col_after = "10">
>        <tree type = "240200" label = "0" typeLabel = "Constant" pos = "35" length = "1" line_before = "3" col_before = "9" line_after = "3" col_after = "10"/>
>       </tree>
>     </tree>
>
> We have updated gumtree so that we require less information to exchange ASTs, the new format is like that :
>
> <root>
> <context></context>
> <tree type="Module" pos="0" length="105">
>   <tree type="Import" pos="0" length="12">
>     <tree type="alias" label="whois" pos="0" length="6">
>     </tree>
>   </tree>
> </tree>
> </root>
>
> I don't know if it's easy to retrieve pos and length instead of columns / lines, but I bet the modifications on type being now the same as typeLabel, typeLabel being removed, and label being optional should be easy to implement.

I'm not sure to understand the example output.  Why is the pos always 0?

julia

**Comment by jrfaller** [comment]
Hi Julia!

It's not the best picked example indeed :) the pos is always zero because these three nodes are nodes starting at the beginning of the file. More generally, pos is the index in character sequence where an AST node begins, and length the number of characters contained in the node.

Full example with Python : 
~~~
import whois

def show_whois():
  w = whois.whois("foo.org")
  print(w)
~~~

Gives this (I know the alias nodes are not treated well by Python's asttparsers, pos is not correct for this node)

~~~
<root>
<context></context>
<tree type="Module" pos="0" length="71">
  <tree type="Import" pos="0" length="12">
    <tree type="alias" label="whois" pos="0" length="6">
    </tree>
  </tree>
  <tree type="FunctionDef" label="show_whois" pos="14" length="57">
    <tree type="arguments" pos="14" length="3">
      <tree type="args" pos="14" length="3">
      </tree>
      <tree type="defaults" pos="14" length="3">
      </tree>
    </tree>
    <tree type="body" pos="34" length="37">
      <tree type="Assign" pos="34" length="26">
        <tree type="NameStore" label="w" pos="34" length="1">
        </tree>
        <tree type="Call" pos="38" length="22">
          <tree type="AttributeLoad" pos="38" length="11">
            <tree type="NameLoad" label="whois" pos="38" length="5">
            </tree>
            <tree type="attr" label="whois" pos="38" length="11">
            </tree>
          </tree>
          <tree type="Str" label="foo.org" pos="50" length="9">
          </tree>
        </tree>
      </tree>
      <tree type="Print" pos="63" length="8">
        <tree type="NameLoad" label="w" pos="69" length="1">
        </tree>
      </tree>
    </tree>
    <tree type="decorator_list" pos="14" length="57">
    </tree>
  </tree>
</tree>
</root>
~~~

**Comment by JuliaLawall** [comment]
On Fri, 4 Oct 2019, Jean-Rémy Falleri wrote:

>
> Hi Julia!
>
> It's not the best picked example indeed :) the pos is always zero because
> these three nodes are nodes starting at the beginning of the file. More
> generally, pos is the index in character sequence where an AST node begins,
> and length the number of characters contained in the node.

OK, our pos and length fields are then ok, but the line and column
information should go?

julia

**Comment by jrfaller** [comment]
Hi Julia,

It's not a problem if it stays because the unknown attributes are ignored by our XML parser, so I think we can leave them because if I recall it was making the job easier when using GumTree for correlations on snippets. Therefore the only change is to rename typeLabel to type and remove the previous type. If it was possible to avoid putting a label attribute when there is no label on a node it would be great since it's not guaranteed that the empty string will account for an empty label in future versions of gumtree (for instance it's not practical in situations such as parsing `String s = ""`).

**Comment by JuliaLawall** [comment]
I think that I have made the requested changes.  Could you check it?

thanks,
julia

**Comment by jrfaller** [comment]
Tried it on a couple files, I think this is OK, thanks a lot Julia!
