### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by andreytikhonov588** [GumTreeDiff/cgum#14]
Don't unerstand how to work with this charm tool. I installed it on my Ubuntu mashine. What can I do to compare two C  code trees

**Comment by jrfaller** [comment]
Take a look here : https://github.com/GumTreeDiff/gumtree/wiki/Getting-Started

**Comment by andreytikhonov588** [comment]
Thanks a lot for your help. I managed to build the GumTreeDiff and cgum, run it and compare C files on Ubuntu. Just one more question. Is it possible to build and install cgum on Windows? Thanks in advance.

**Comment by jrfaller** [comment]
I think the easiest way is by using our docker image : https://github.com/GumTreeDiff/gumtree/tree/develop/docker that bundles everything and works on windows!

**Comment by andreytikhonov588** [comment]
Again, many thanks for your help. My task is to get edit script for two C files (more precisely between their AST) . I see solutions fo Java. For example - https://github.com/GumTreeDiff/gumtree/tree/develop/core/src/main/java/com/github/gumtreediff/actions and https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API. But I don't understand how to get edit script for C files.

**Comment by jrfaller** [comment]
The solution described in https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API also works for C files as long as you have cgum correctly installed. The code was outdated, I updated it to be consistent with the latest commit of GumTree.
