### ISSUE TITLE
Don't know how to export path

### ISSUE THREAD

**Issue by bomian98** [GumTreeDiff/cgum#15]
I'm not familiar with linux and can't use cgum.

I clone this repo in "/home/user/gitrepo/cgum" and use the command in the RADME.md.
I get those files:
```
cgum   commons     flag_cocci.cmi  flag_cocci.ml  main.cmi  main.ml      Makefile         parsing_c  standard.h  tools
cgumw  Dockerfile  flag_cocci.cmo  globals        main.cmo  make_config  Makefile.config  README.md  tests
```
Are those correct?

For export path, is the following command is correct?
```
export PATH=$PATH:/home/user/gitrepo/cgum
```
Besides, I type "cgum" in cgum dir, it told me 
```
Command 'cgum' not found
```
I don't know how to deal with it

**Comment by jrfaller** [comment]
Maybe you can try to use the Docker image ? https://hub.docker.com/u/gumtreediff

Cheers!

**Comment by npalix** [comment]
Could you try the following ?
```
cd /home/user/gitrepo/cgum
ls -l
./cgum
```
