### ISSUE TITLE
Installation cgum in Windows

### ISSUE THREAD

**Issue by SherloqueChang** [GumTreeDiff/cgum#18]
I'd like to use GumTree Java API to get the diff information ( edit actions ) in C code files, but I couldn't find a way to install cgum in Windows environment. Can this be achieved?

**Comment by jrfaller** [comment]
Hi!

There are several solutions: you can try our Docker image (https://hub.docker.com/r/gumtreediff/gumtree) or you can try the tree-sitter based parser that was just committed into GumTree main!
