### ISSUE TITLE
How to get all possible AST node type

### ISSUE THREAD

**Issue by niuxu18** [GumTreeDiff/cgum#3]
For example, function call node is parsed as FunCall, function definition node is parsed as Defition... I wonder if there is a full list about the map of ast node type?? Thanks for your help

**Comment by npalix** [comment]
Hi,

You could check xmlify.ml

https://github.com/GumTreeDiff/cgum/blob/master/parsing_c/xmlify.ml

**Comment by niuxu18** [comment]
thanks for your help there ^ ^
