### ISSUE TITLE
Error: Unbound module Big_int

### ISSUE THREAD

**Issue by iamkeyur** [GumTreeDiff/cgum#7]
```
File "./flag_parsing_c.ml", line 219, characters 5-20:
Error: Unbound module Big_int
make[3]: *** [Makefile:139: flag_parsing_c.cmo] Error 2
make[3]: Leaving directory '/var/tmp/pamac-build-keyur/cgum-git/src/cgum/parsing_c'
make[2]: *** [Makefile:149: parsing_c] Error 2
make[2]: Leaving directory '/var/tmp/pamac-build-keyur/cgum-git/src/cgum'
make[1]: *** [Makefile:142: subdirs] Error 1
make[1]: Leaving directory '/var/tmp/pamac-build-keyur/cgum-git/src/cgum'
make: *** [Makefile:131: byte] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

I have been trying to install cgum since last one week. I have tried everything that was available on the internet regarding this issue. Any help would be appreciated.

**Comment by iamkeyur** [comment]
Big num was removed from core in recent ocaml releases. So, cgum can only be compiled by ocaml version upto 4.05.0

**Comment by jrfaller** [comment]
OK, apparently still distributed here : https://github.com/ocaml/num and superseeded by this one : https://github.com/ocaml/Zarith

**Comment by jrfaller** [comment]
Strange,  on mac os I manage to compile it with `The OCaml toplevel, version 4.07.1` I think this is because I have `ocaml-num` installed (via brew). Also available via opam (`https://opam.ocaml.org/packages/num/`).

**Comment by iamkeyur** [comment]
I have num package installed too. But, for me it's not working.
